export const categories = [
  {
    id: 'tops',
    name: 'Tops & Rompers',
    description: 'Soft cotton tees, bodysuits, rompers, and everyday dresses for newborns and toddlers',
  },
  {
    id: 'bottoms',
    name: 'Pants & Bloomers',
    description: 'Gentle cotton trousers, shorts, and bloomers cut for nappy changes and play',
  },
  {
    id: 'outerwear',
    name: 'Cardigans & Jackets',
    description: 'Light cotton layers and soft jackets for cooler mornings and evening outings',
  },
  {
    id: 'accessories',
    name: 'Baby Essentials',
    description: 'Cotton bibs, beanies, mittens, and booties for everyday Nigeria weather',
  },
];

const img = (id) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=900&q=80`;

const SIZES = ['0-3M', '3-6M', '6-12M', '12-18M', '18-24M'];

export const products = [
  {
    id: 'b1',
    name: 'Cloud Cotton Crew Tee',
    brand: 'NG BABIES',
    category: 'tops',
    price: 3400,
    description:
      'A lightweight cotton crew tee with a soft neckline that slips on without a struggle. The straight hem sits neatly over nappies, and the fabric stays breathable through warm Lagos afternoons. Available in 0-3M, 3-6M, 6-12M, 12-18M, and 18-24M, with nationwide delivery across Nigeria.',
    sizes: SIZES,
    colors: ['White', 'Cream', 'Sky Blue'],
    images: [
      img('1622290319146-7b63df48a635'),
      img('1589452121483-c14e331408b1'),
    ],
    featured: true,
    newSeason: true,
    exclusive: false,
  },
  {
    id: 'b2',
    name: 'Sunrise Stripe Cotton Tee',
    brand: 'NG BABIES',
    category: 'tops',
    price: 3600,
    description:
      'Fine cotton jersey with a quiet stripe, made for first outings and everyday play. Shoulder room is easy, and the short sleeves leave little arms free. Choose from 0-3M through 18-24M and have it delivered anywhere in Nigeria.',
    sizes: SIZES,
    colors: ['White', 'Navy', 'Sky Blue'],
    images: [
      img('1569974641446-22542de88536'),
      img('1622290291720-ac961c43ee30'),
    ],
    featured: false,
    newSeason: true,
    exclusive: false,
  },
  {
    id: 'b3',
    name: 'Lagos Breeze Cotton Romper',
    brand: 'NG BABIES',
    category: 'tops',
    price: 6200,
    compareAtPrice: 6900,
    description:
      'A one-piece cotton romper with snap openings that make nappy changes quicker. The soft knit does not cling, so babies can stretch, nap, and crawl without fuss. Sized 0-3M to 18-24M and sent with nationwide delivery in Nigeria.',
    sizes: SIZES,
    colors: ['Ivory', 'Sage', 'Blush'],
    images: [
      img('1768198566391-298fc185bf1d'),
      img('1775650076115-154d437bc717'),
    ],
    featured: true,
    newSeason: true,
    exclusive: false,
  },
  {
    id: 'b4',
    name: 'Ivory Petal Cotton Dress',
    brand: 'NG BABIES',
    category: 'tops',
    price: 6800,
    compareAtPrice: 7500,
    description:
      'A simple cotton day dress with a gentle neckline and a hem that moves when toddlers walk. It is light enough for church visits and family gatherings without feeling stiff. Offered in 0-3M, 3-6M, 6-12M, 12-18M, and 18-24M.',
    sizes: SIZES,
    colors: ['Ivory', 'White', 'Blush'],
    images: [
      img('1764665818844-7cb4f51935d5'),
      img('1616656911313-3394ccb03318'),
    ],
    featured: true,
    newSeason: true,
    exclusive: false,
  },
  {
    id: 'b5',
    name: 'Garden Light Cotton Dress',
    brand: 'NG BABIES',
    category: 'tops',
    price: 7800,
    description:
      'Soft cotton with a bit of swing in the skirt, cut for birthday photos and ordinary Sundays alike. The fabric washes well and stays kind on sensitive skin. Sizes run from 0-3M to 18-24M, and we deliver nationwide in Nigeria.',
    sizes: SIZES,
    colors: ['White', 'Blush', 'Sage'],
    images: [
      img('1684244160171-97f5dac39204'),
      img('1616656911313-3394ccb03318'),
    ],
    featured: true,
    newSeason: false,
    exclusive: false,
  },
  {
    id: 'b6',
    name: 'Soft Foldover Cotton Bloomers',
    brand: 'NG BABIES',
    category: 'bottoms',
    price: 4200,
    description:
      'These cotton bloomers sit gently at the waist and stretch for a full nappy. The short leg stays put when babies kick, without leaving red marks. Available in 0-3M through 18-24M.',
    sizes: SIZES,
    colors: ['Cream', 'Sage', 'Ivory'],
    images: [
      img('1572005658511-783ef941af3b'),
      img('1522771930-78848d9293e8'),
    ],
    featured: false,
    newSeason: false,
    exclusive: false,
  },
  {
    id: 'b7',
    name: 'Everyday Cotton Pull-On Trousers',
    brand: 'NG BABIES',
    category: 'bottoms',
    price: 5400,
    description:
      'Pull-on cotton trousers with a soft waist that clears a nappy and still looks tidy. They pair with our tees for market days and nursery drop-off. Sized 0-3M, 3-6M, 6-12M, 12-18M, and 18-24M, with delivery across Nigeria.',
    sizes: SIZES,
    colors: ['Navy', 'Olive', 'Charcoal'],
    images: [
      img('1605644235751-709c7254e3e3'),
      img('1549588974-98aae09c3845'),
    ],
    featured: false,
    newSeason: true,
    exclusive: false,
  },
  {
    id: 'b8',
    name: 'Playday Cotton Shorts',
    brand: 'NG BABIES',
    category: 'bottoms',
    price: 3900,
    description:
      'Easy cotton shorts with a covered elastic waist for warm afternoons at home or outdoors. The rise is generous so they do not ride down during crawling. Sizes 0-3M to 18-24M.',
    sizes: SIZES,
    colors: ['Sky Blue', 'Olive', 'Cream'],
    images: [
      img('1766918780914-5df4a5a98c44'),
      img('1632337948797-ba161d29532b'),
    ],
    featured: false,
    newSeason: false,
    exclusive: false,
  },
  {
    id: 'b9',
    name: 'Comfort Cotton Leggings',
    brand: 'NG BABIES',
    category: 'bottoms',
    price: 4500,
    description:
      'Soft cotton leggings that stretch over a nappy and stay in place under dresses or long tees. The ankle cuffs are light, not tight. Available in 0-3M, 3-6M, 6-12M, 12-18M, and 18-24M.',
    sizes: SIZES,
    colors: ['Charcoal', 'Navy', 'Ivory'],
    images: [
      img('1705329584512-b210927265e0'),
      img('1766918780916-228d10b071be'),
    ],
    featured: false,
    newSeason: false,
    exclusive: false,
  },
  {
    id: 'b10',
    name: 'Weekend Cotton Tee and Shorts Set',
    brand: 'NG BABIES',
    category: 'tops',
    price: 9800,
    compareAtPrice: 10900,
    description:
      'A matching cotton tee and shorts set for weekends, visits, and first birthdays. Both pieces are soft, breathable, and cut with room to grow. Sizes run 0-3M to 18-24M, and we offer nationwide delivery in Nigeria.',
    sizes: SIZES,
    colors: ['Sky Blue', 'Cream', 'Navy'],
    images: [
      img('1768198566789-fa307df579f1'),
      img('1549588974-98aae09c3845'),
    ],
    featured: true,
    newSeason: true,
    exclusive: false,
  },
  {
    id: 'b11',
    name: 'Harmattan Cotton Two-Piece Set',
    brand: 'NG BABIES',
    category: 'outerwear',
    price: 11800,
    compareAtPrice: 12500,
    description:
      'A long-sleeve cotton top and matching trousers for cooler harmattan mornings. The set layers easily and still feels light once the sun is up. Available in 0-3M through 18-24M, delivered nationwide across Nigeria.',
    sizes: SIZES,
    colors: ['Camel', 'Cream', 'Olive'],
    images: [
      img('1758851723032-dfe4bedf18d2'),
      img('1766918780914-5df4a5a98c44'),
    ],
    featured: true,
    newSeason: true,
    exclusive: true,
  },
  {
    id: 'b12',
    name: 'Moonlight Cotton Sleep Set',
    brand: 'NG BABIES',
    category: 'tops',
    price: 9900,
    description:
      'A two-piece cotton sleep set with a soft tee and relaxed trousers for naps and overnight. Seams are flat enough for restless sleepers, and the fabric washes without getting scratchy. Sizes 0-3M, 3-6M, 6-12M, 12-18M, and 18-24M, with delivery across Nigeria.',
    sizes: SIZES,
    colors: ['Ivory', 'Sage', 'Sky Blue'],
    images: [
      img('1522771930-78848d9293e8'),
      img('1589452121483-c14e331408b1'),
    ],
    featured: true,
    newSeason: true,
    exclusive: false,
  },
  {
    id: 'b13',
    name: 'Sunday Cotton Formal Set',
    brand: 'NG BABIES',
    category: 'tops',
    price: 10800,
    compareAtPrice: 11800,
    description:
      'A neat cotton shirt and trousers set for dedications, church, and family photos. It looks considered without feeling stiff on a wriggling baby. Available from 0-3M to 18-24M, with nationwide delivery in Nigeria.',
    sizes: SIZES,
    colors: ['White', 'Ivory', 'Navy'],
    images: [
      img('1549588974-98aae09c3845'),
      img('1622290319146-7b63df48a635'),
    ],
    featured: true,
    newSeason: true,
    exclusive: false,
  },
  {
    id: 'b14',
    name: 'Naming Day Cotton Formal Set',
    brand: 'NG BABIES',
    category: 'tops',
    price: 11400,
    description:
      'A polished cotton two-piece for naming ceremonies and celebration days. The finish is clean, and the cotton stays comfortable through long greetings and photos. Sizes 0-3M, 3-6M, 6-12M, 12-18M, and 18-24M.',
    sizes: SIZES,
    colors: ['Cream', 'White', 'Blush'],
    images: [
      img('1764665818844-7cb4f51935d5'),
      img('1684244160171-97f5dac39204'),
    ],
    featured: false,
    newSeason: true,
    exclusive: true,
  },
  {
    id: 'b15',
    name: 'Soft Cotton Cardigan',
    brand: 'NG BABIES',
    category: 'outerwear',
    price: 7600,
    description:
      'A light cotton cardigan for air-conditioned rooms and early evening air. Buttons are easy for grown-ups, and the knit is soft against skin. Sizes 0-3M to 18-24M, delivered nationwide in Nigeria.',
    sizes: SIZES,
    colors: ['Cream', 'Camel', 'Sage'],
    images: [
      img('1632337948797-ba161d29532b'),
      img('1556905055-8f358a7a47b2'),
    ],
    featured: true,
    newSeason: true,
    exclusive: false,
  },
  {
    id: 'b16',
    name: 'Stroller Cotton Jacket',
    brand: 'NG BABIES',
    category: 'outerwear',
    price: 8900,
    compareAtPrice: 9600,
    description:
      'A cotton jacket with a simple front close, made to throw over a romper for walks and car rides. It packs small and does not overheat once you are indoors. Sizes 0-3M through 18-24M.',
    sizes: SIZES,
    colors: ['Navy', 'Camel', 'Charcoal'],
    images: [
      img('1758851723032-dfe4bedf18d2'),
      img('1766918780916-228d10b071be'),
    ],
    featured: true,
    newSeason: false,
    exclusive: false,
  },
  {
    id: 'b17',
    name: 'Hooded Cotton Zip Jacket',
    brand: 'NG BABIES',
    category: 'outerwear',
    price: 8200,
    description:
      'A hooded cotton jacket for breezy mornings and late harmattan evenings. The zip is covered at the chin, and the hood sits without flopping into little eyes. Available in 0-3M, 3-6M, 6-12M, 12-18M, and 18-24M.',
    sizes: SIZES,
    colors: ['Olive', 'Navy', 'Cream'],
    images: [
      img('1766918780914-5df4a5a98c44'),
      img('1758851723032-dfe4bedf18d2'),
    ],
    featured: false,
    newSeason: true,
    exclusive: false,
  },
  {
    id: 'b18',
    name: 'Cotton Bandana Bib Pair',
    brand: 'NG BABIES',
    category: 'accessories',
    price: 3200,
    description:
      'Two cotton bandana bibs that catch dribbles without a bulky neckline. They fasten softly and wash clean after meals. One adjustable size works from 0-3M through 18-24M, and we deliver across Nigeria.',
    sizes: ['0-3M', '3-6M', '6-12M', '12-18M', '18-24M'],
    colors: ['White', 'Sage', 'Blush'],
    images: [
      img('1622290291720-ac961c43ee30'),
      img('1569974641446-22542de88536'),
    ],
    featured: false,
    newSeason: false,
    exclusive: false,
  },
  {
    id: 'b19',
    name: 'Knit Cotton Beanie and Mitten Set',
    brand: 'NG BABIES',
    category: 'accessories',
    price: 3800,
    description:
      'A cotton knit beanie and matching mittens for cooler mornings and air-conditioned halls. The knit stretches, so it stays on without pinching. Fits 0-3M to 18-24M and ships nationwide in Nigeria.',
    sizes: SIZES,
    colors: ['Cream', 'Camel', 'Sky Blue'],
    images: [
      img('1556905055-8f358a7a47b2'),
      img('1766918780916-228d10b071be'),
    ],
    featured: false,
    newSeason: true,
    exclusive: false,
  },
  {
    id: 'b20',
    name: 'Soft Cotton Stay-On Booties',
    brand: 'NG BABIES',
    category: 'accessories',
    price: 3500,
    description:
      'Soft cotton booties with a gentle cuff so they stay on tiny feet. They are meant for home, pram rides, and first outings, not hard outdoor walking. Sized 0-3M, 3-6M, 6-12M, 12-18M, and 18-24M.',
    sizes: SIZES,
    colors: ['Cream', 'Ivory', 'Blush'],
    images: [
      img('1766918780916-228d10b071be'),
      img('1556905055-8f358a7a47b2'),
    ],
    featured: false,
    newSeason: false,
    exclusive: false,
  },
];
