export const categories = [
  { id: 'tops', name: 'Tops', description: 'Shirts, blouses, and everyday knits' },
  { id: 'bottoms', name: 'Bottoms', description: 'Trousers, jeans, and skirts' },
  { id: 'outerwear', name: 'Outerwear', description: 'Jackets and coats for every season' },
  { id: 'accessories', name: 'Accessories', description: 'Bags, scarves, and finishing touches' },
];

const img = (id, w = 800, h = 1000) => `https://picsum.photos/seed/cloth-${id}/${w}/${h}`;

export const products = [
  {
    id: 'p1',
    name: 'Linen Easy Shirt',
    brand: 'Maison Lane',
    category: 'tops',
    price: 68,
    description: 'Breathable linen-blend shirt with a relaxed silhouette. Perfect for warm days and layering.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Ivory', 'Sage', 'Navy'],
    images: [img('p1a'), img('p1b')],
    featured: true,
    newSeason: true,
    exclusive: false,
  },
  {
    id: 'p2',
    name: 'Ribbed Mock Neck',
    brand: 'Atelier Studio',
    category: 'tops',
    price: 42,
    compareAtPrice: 58,
    description: 'Soft stretch rib knit with a clean mock neck. A wardrobe staple for cooler evenings.',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Cream', 'Burgundy'],
    images: [img('p2a'), img('p2b')],
    featured: true,
    newSeason: false,
    exclusive: false,
  },
  {
    id: 'p3',
    name: 'Wide-Leg Trouser',
    brand: 'Nordic Form',
    category: 'bottoms',
    price: 88,
    description: 'High-rise wide-leg trousers with a fluid drape and side zip. Tailored yet comfortable.',
    sizes: ['24', '26', '28', '30', '32'],
    colors: ['Black', 'Camel', 'Olive'],
    images: [img('p3a'), img('p3b')],
    featured: true,
    newSeason: true,
    exclusive: true,
  },
  {
    id: 'p4',
    name: 'Vintage Straight Jean',
    brand: 'Denim Co.',
    category: 'bottoms',
    price: 78,
    description: 'Classic straight-leg denim with a soft wash and mid rise. Broken-in feel from day one.',
    sizes: ['24', '26', '28', '30', '32', '34'],
    colors: ['Indigo', 'Light Wash'],
    images: [img('p4a'), img('p4b')],
    featured: false,
    newSeason: false,
    exclusive: false,
  },
  {
    id: 'p5',
    name: 'Pleated Midi Skirt',
    brand: 'Maison Lane',
    category: 'bottoms',
    price: 72,
    compareAtPrice: 95,
    description: 'Lightweight pleated midi with elastic waist. Moves beautifully with every step.',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Rust', 'Forest'],
    images: [img('p5a'), img('p5b')],
    featured: false,
    newSeason: false,
    exclusive: false,
  },
  {
    id: 'p6',
    name: 'Structured Blazer',
    brand: 'Atelier Studio',
    category: 'outerwear',
    price: 148,
    description: 'Single-breasted blazer with soft shoulder and lined finish. Desk-to-dinner ready.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Charcoal', 'Cream', 'Navy'],
    images: [img('p6a'), img('p6b')],
    featured: true,
    newSeason: true,
    exclusive: false,
  },
  {
    id: 'p7',
    name: 'Quilted Crop Jacket',
    brand: 'Nordic Form',
    category: 'outerwear',
    price: 118,
    description: 'Lightweight quilted jacket with stand collar and zip front. Ideal transitional layer.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Stone', 'Olive'],
    images: [img('p7a'), img('p7b')],
    featured: false,
    newSeason: false,
    exclusive: true,
  },
  {
    id: 'p8',
    name: 'Wool Blend Coat',
    brand: 'Maison Lane',
    category: 'outerwear',
    price: 198,
    description: 'Long wool-blend coat with notch lapel and hidden buttons. A cold-weather essential.',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Camel', 'Black'],
    images: [img('p8a'), img('p8b')],
    featured: true,
    newSeason: true,
    exclusive: false,
  },
  {
    id: 'p9',
    name: 'Mini Crossbody Bag',
    brand: 'Atelier Studio',
    category: 'accessories',
    price: 58,
    description: 'Compact crossbody in smooth vegan leather with adjustable strap and magnetic flap.',
    sizes: ['One Size'],
    colors: ['Black', 'Tan', 'Wine'],
    images: [img('p9a'), img('p9b')],
    featured: true,
    newSeason: false,
    exclusive: true,
  },
  {
    id: 'p10',
    name: 'Cashmere Feel Scarf',
    brand: 'Nordic Form',
    category: 'accessories',
    price: 36,
    compareAtPrice: 48,
    description: 'Ultra-soft oversized scarf with fringed edges. Adds instant polish to any look.',
    sizes: ['One Size'],
    colors: ['Ivory', 'Grey', 'Blush'],
    images: [img('p10a'), img('p10b')],
    featured: false,
    newSeason: false,
    exclusive: false,
  },
  {
    id: 'p11',
    name: 'Silk Bandana',
    brand: 'Maison Lane',
    category: 'accessories',
    price: 28,
    description: 'Printed silk-touch bandana for hair, neck, or bag accents.',
    sizes: ['One Size'],
    colors: ['Noir Print', 'Blue Print'],
    images: [img('p11a'), img('p11b')],
    featured: false,
    newSeason: true,
    exclusive: false,
  },
  {
    id: 'p12',
    name: 'Cropped Tee',
    brand: 'Atelier Studio',
    category: 'tops',
    price: 32,
    description: 'Organic cotton cropped tee with a boxy cut and reinforced neckline.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Black', 'Sky'],
    images: [img('p12a'), img('p12b')],
    featured: false,
    newSeason: false,
    exclusive: false,
  },
];
